export const products = [
  {
    id: 1,
    name: "Arroz Diana 1kg",
    category: "Despensa",
    price: 3500,
    image: "/images/products/arroz.jpg",
    description: "Arroz blanco Diana de 1 kilogramo.",
    stock: 50,
    brand: "Diana",
  },
  {
    id: 2,
    name: "Aceite Vegetal 1L",
    category: "Despensa",
    price: 8500,
    image: "/images/products/aceite.jpg",
    description: "Aceite vegetal de 1 litro.",
    stock: 35,
    brand: "Mazorca",
  },
  {
    id: 3,
    name: "Huevos Docena",
    category: "Lácteos y Huevos",
    price: 12000,
    image: "/images/products/huevos.jpg",
    description: "Docena de huevos frescos.",
    stock: 40,
    brand: "Granja",
  },
  {
    id: 4,
    name: "Leche Entera 1L",
    category: "Lácteos y Huevos",
    price: 4500,
    image: "/images/products/leche.jpg",
    description: "Leche entera pasteurizada de 1 litro.",
    stock: 60,
    brand: "Colanta",
  },
  {
    id: 5,
    name: "Pan Blanco 500g",
    category: "Panadería",
    price: 3800,
    image: "/images/products/pan.jpg",
    description: "Pan blanco de 500 gramos.",
    stock: 25,
    brand: "Bimbo",
  },
  {
    id: 6,
    name: "Café Tostado Molido 250g",
    category: "Bebidas",
    price: 15000,
    image: "/images/products/cafe.jpg",
    description: "Café tostado y molido de 250 gramos.",
    stock: 30,
    brand: "Sello Rojo",
  },
  {
    id: 7,
    name: "Azúcar Blanca 1kg",
    category: "Despensa",
    price: 3200,
    image: "/images/products/azucar.jpg",
    description: "Azúcar blanca refinada de 1 kilogramo.",
    stock: 55,
    brand: "Incauca",
  },
  {
    id: 8,
    name: "Sal Yodada 500g",
    category: "Despensa",
    price: 1800,
    image: "/images/products/sal.jpg",
    description: "Sal yodada de 500 gramos.",
    stock: 70,
    brand: "Refisal",
  },
  {
    id: 9,
    name: "Gaseosa Coca-Cola 1.5L",
    category: "Bebidas",
    price: 5500,
    image: "/images/products/gaseosa.jpg",
    description: "Gaseosa Coca-Cola de 1.5 litros.",
    stock: 45,
    brand: "Coca-Cola",
  },
  {
    id: 10,
    name: "Detergente en Polvo 1kg",
    category: "Aseo",
    price: 9000,
    image: "/images/products/detergente.jpg",
    description: "Detergente en polvo de 1 kilogramo.",
    stock: 25,
    brand: "Ariel",
  },
  {
    id: 11,
    name: "Papas Fritas Margarita 150g",
    category: "Snacks",
    price: 4500,
    image: "/images/products/papas.jpg",
    description: "Papas fritas Margarita de 150 gramos.",
    stock: 35,
    brand: "Margarita",
  },
  {
    id: 12,
    name: "Chocolatinas Jet 10u",
    category: "Snacks",
    price: 8000,
    image: "/images/products/chocolate.jpg",
    description: "Paquete de 10 chocolatinas Jet.",
    stock: 20,
    brand: "Jet",
  },
];
